 default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

 development:
  <<: *default
  database: qa_development

 test:
  <<: *default
  database: qa_test